[project]
name = "ws"
version = "0.1.0"
description = "Tool to manage multiple copies of projects that span multiple repos"
readme = "README.md"
authors = [
    { name = "Sebastian Mestre", email = "mestresebastianunr@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6",
]

[project.scripts]
ws = "ws:main"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pytest>=8",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
target-version = ["py311"]

[build-system]
requires = ["uv_build>=0.11.24,<0.12.0"]
build-backend = "uv_build"
